version: "3.3"
services:
  app:
    container_name: docker-example-ui
    build: .
    ports: 
      - 2080:2080

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: devon
      POSTGRES_DB: meals
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
