version: "3.3"
services:
  app:
    container_name: docker-example-ui
    build: .
    depends_on:
      - db
    ports: 
      - 2080:2080
    environment:
      PGUSER: devon
      PGHOST: db
      PGPASSWORD: secret
      PGDATABASE: meals
      PGPORT: 5432

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: devon
      POSTGRES_DB: meals
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata:
